### ISSUE TITLE
Past books/magazines no longer being downloaded

### ISSUE THREAD

**Issue by tripplehelix** [artivis/rpipress-downloader#17]
Seems downloading books/magazines with -a no longer downloads them all.

**Comment by Xybr** [comment]
When I attempt to run the script, I get the following error message: 

Traceback` (most recent call last):
  File "/home/mike/anaconda3/bin/rpipress-downloader", line 138, in <module>
    last_issue = soup.find('section', class_="c-latest-issue").findChild("a")['href'].split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'findChild'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mike/anaconda3/bin/rpipress-downloader", line 140, in <module>
    raise Exception('Could not find latest ' + magazine.name + ' issue number')
Exception: Could not find latest HackSpace issue number

When looking at the website, it appears they've made some changes that broke the script.

**Comment by tripplehelix** [comment]
Yea, looks like they no longer offer their mags for free. Not much you can do now except buy them.
