### ISSUE TITLE
Wireframe has moved?

### ISSUE THREAD

**Issue by tripplehelix** [artivis/rpipress-downloader#3]
```
14:52:46 ▶ rpipress-downloader -a
Latest CustomPC issue is N°234
Latest HackSpace issue is N°65
Latest HelloWorld issue is N°20
Latest MagPi issue is N°128
Traceback (most recent call last):
  File "/home/tom/.local/bin/rpipress-downloader", line 130, in <module>
    last_issue = soup.find('section', class_="c-latest-issue").findChild("a")['href'].split('/')[-1]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'findChild'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/.local/bin/rpipress-downloader", line 132, in <module>
    raise Exception('Could not find latest ' + magazine.name + ' issue number')
Exception: Could not find latest Wireframe issue number
```

**Comment by tripplehelix** [comment]
Looks like it's all falling apart
```
[13:31:02 ▶ rpipress-downloader
Traceback (most recent call last):
  File "/home/tom/.local/bin/rpipress-downloader", line 129, in <module>
    last_issue = soup.find('section', class_="c-latest-issue").findChild("a")['href'].split('/')[-1]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'findChild'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tom/.local/bin/rpipress-downloader", line 131, in <module>
    raise Exception('Could not find latest ' + magazine.name + ' issue number')
Exception: Could not find latest CustomPC issue number](url)
```

**Comment by artivis** [comment]
Hi,

Thanks for reporting these. 
It seems that [Wireframe has closed down](https://www.gamesindustry.biz/four-years-and-70-issues-later-why-wireframe-magazine-is-closing-down). The issues website now points to [whynowgaming.com](https://whynowgaming.com/). 
As for customPC, it still exist but the former download website onw redirects to [custompc.com](https://www.custompc.com/).
Given that the old issues can't be retrieved from the same URLs anymore, I'm simply gonna disable those magazines in the script.
